soc: qcom: event_timer: Fix compilation after linux v4.19.210 merge
 Commit b9a1ac8 had removed the declaration of "head" and "next" and converted them to "rb_root".
 Adapt the new declaration at drivers/soc/qcom/event_timer.c.

 Fixes the following compilation errors:

 ../drivers/soc/qcom/event_timer.c:47:3: error: field designator 'head' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
         .head = RB_ROOT,
          ^
 ../drivers/soc/qcom/event_timer.c:48:3: error: field designator 'next' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
         .next = NULL,
          ^

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
Signed-off-by: pix106 <sbordenave@gmail.com>